version: '3'

services:
  nicky-nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    container_name: nicky-nginx
    ports:
      - 443:443
    restart: always

  nicky-mysql:
    image: mysql:oracle
    platform: linux/arm64/v8
    container_name: nicky-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nicky
    restart: always

  nicky-shell:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nickyshell
    container_name: nicky-shell
    restart: always
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - TERM=xterm

