version: '3'

services:

  nicky-nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    container_name: nicky-nginx
    ports:
      - 443:443
    restart: always

  nicky-shell:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nickyshell
    container_name: nicky-shell
    restart: always
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - TERM=xterm

