FROM node as build

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY ./frontend /frontend
WORKDIR /frontend

RUN npm install && npm run build


FROM nginx

COPY --from=build /frontend/dist /frontend
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/cert /etc/cert

CMD ["nginx", "-g", "daemon off;"]
